POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Curso de Node"
}

###

GET http://localhost:3333/courses?orderBy=title

###
GET http://localhost:3333/courses/cf50c27b-d589-4008-8658-4f3250985fb1

###
PUT http://localhost:3333/courses/6ad97416-1f60-42bf-b866-8b1dc789765e
Content-Type: application/json

{
  "title": "Outro curso"
}

###
DELETE http://localhost:3333/courses/6ad97416-1f60-42bf-b866-8b1dc789765e
