POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Curso de Tailwind"
}

###

GET http://localhost:3333/courses

###
GET http://localhost:3333/courses/6sdasd

###
PUT http://localhost:3333/courses/adsasdad
Content-Type: application/json

{
  "title": "Outro curso"
}

###
DELETE http://localhost:3333/courses/6d8c014a-c5ea-4126-ad4f-6eb0699aa03e
Content-Type: application/json

{
  "title": "Outro curso"
}